### PR TITLE
Add some communities from Istanbul, Turkey

### PR DESCRIPTION
**Pull request by caniknermin**
Hello,
I added Women.Digital  and R-Ladies communities from Istanbul, Turkey. 
I guess, I need a little bit help to edit cities.json file (add Istanbul on the world map). 
Thanks for your great idea!

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@caniknermin please add istanbul to the cities list, The code for istanbul is given below:
```json
  {
    "name": "Istanbul",
    "slug": "Istanbul",
    "country": "turkey",
    "top": 252,
    "left": 525
  },
```
Add the code to https://github.com/prisma/women-world-wide/blob/8ee40874ae074b204f969054d8cb0bee6513e5ed/src/data/cities.json#L156 (Line 156)

FYI: the source code uses css top and left attributes to plot the point on map. @etelsv This must be documented somewhere in the readme. I had the same doubt when i contributed to the project for the first time. I had to figure it out myself 😄

**Comment by caniknermin** [comment]
Hello,
I added Istanbul city to cities list thanks to @gautamkrishnar 🥇

**Comment by caniknermin** [comment]
@etelsv @kuldar  I'm looking forward to adding some organizations from Istanbul! Do you need extra information about my pull request? Many thanks for the great project. :)

**Comment by etelsv** [comment]
Looks great! Just merged the PR! Thanks so much for adding the organizations!

**Pull request merged**
