### PR TITLE
Add Django girls Turkey community

### PR DESCRIPTION
**Pull request by neslihanturan**
part of #34 
Django Girls Turkey is added.

### CODE REVIEW

**Comment by janpio** [comment]
FYI: I changed your "Fixes #34" to "part of #34", otherwise the issue will be closed when your PR is merged.

**Review by janpio — APPROVED** [review]

**Comment by etelsv** [comment]
For some reason the image isn't showing up in the preview. Do you know why this might be happening by any chance? I want to make sure the logo is visible 😁

**Comment by neslihanturan** [comment]
Hmm, even though the link is valid I think the lack of SSL certificate on that website causes this issue. Let me check if I can find other links :)

**Comment by neslihanturan** [comment]
This version should work as expected @etelsv

**Comment by etelsv** [comment]
Looks great. Merged! :)

**Pull request merged**
